name: 🐛 Bug Report
description: File a bug report
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              ** BEFORE YOU POST:** Please check whether there is already an open issue on your report here: https://github.com/cline/cline/issues
    - type: markdown
      attributes:
          value: |
              **Important:** All bug reports must be reproducible using Claude 4 Sonnet. Cline uses complex prompts so less capable models may not work as expected.
    - type: textarea
      id: expected-result
      attributes:
          label: What was the expected result, outcome, or action?
          description: Describe what you expected to happen.
          placeholder: Tell us what you expected to see or happen!
      validations:
          required: true
    - type: textarea
      id: observed-result
      attributes:
          label: What was the observed result?
          description: Describe what actually happened instead.
          placeholder: Tell us what you actually saw or what happened!
      validations:
          required: true
    - type: textarea
      id: steps
      attributes:
          label: Steps to reproduce
          description: |
              - Please describe what you were doing before the bug appeared (tool actions, user actions, etc)
              - Mention specific details about your actions (clicks, tool calls, files, etc), that triggered this bug
              - Every detail counts, break down the process into as many steps as needed
          value: |
              1.
              2.
              3.
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Relevant API REQUEST output
          description: Please copy and paste any relevant output. This will be automatically formatted into code, so no need for backticks.
          render: shell
    - type: input
      id: provider
      attributes:
          label: Provider
          description: What provider were you using when the issue occurred?
          placeholder: "e.g., anthropic, openai, gemini, xai"
      validations:
          required: true
    - type: input
      id: model
      attributes:
          label: Model
          description: What model were you using when the issue occurred?
          placeholder: "e.g., claude-4-sonnet, gpt-4o, gemini-2.0-flash-exp, grok-2-1212"
      validations:
          required: true
    - type: input
      id: operating-system
      attributes:
          label: Operating System
          description: What operating system are you using?
          placeholder: "e.g., Windows 11, macOS Sonoma, Ubuntu 22.04"
      validations:
          required: true
    - type: textarea
      id: system-info
      attributes:
          label: System Info
          description: What system information is relevant to the issue?
          placeholder: "e.g., CPU: Intel Core i7-11700K, GPU: NVIDIA GeForce RTX 3070, RAM: 32GB DDR4"
      validations:
          required: true
    - type: input
      id: cline-version
      attributes:
          label: Cline Version
          description: What version of Cline are you using? (You can find this at the bottom of the Settings view)
          placeholder: "e.g., 1.2.3"
      validations:
          required: true
    - type: textarea
      id: additional-context
      attributes:
          label: Additional context/ screenshots
          description: Add any other context about the problem here, such as screenshots or related issues.
